version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: dgarridouma/get-started:part2
    ports:
      - "4000:80"
    networks:
      - webnet
    environment:
      - REDIS_HOST=redis
      
  redis:
    image: redis
    ports:
      - "6379:6379"   
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet

networks:
  webnet:
